plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.feature.podcast.ui"
    compileSdk 36

    defaultConfig {
        minSdk 23

        consumerProguardFiles "consumer-rules.pro"
    }
    buildFeatures {
        dataBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    implementation(project(":common-base"))
    implementation(project(":common-di"))
    implementation(project(":common-navigation"))
    implementation(project(":common-ui-domain"))
    implementation(project(":component-info"))
    implementation(project(":data-local"))
    implementation(project(":feature-podcast-base-domain"))
    implementation(project(":feature-podcast-base-ui"))
    implementation(project(":feature-podcast-domain"))
    implementation(project(":feature-songlist-base-domain"))
    implementation(project(":management-download"))
    implementation(project(":management-filters"))
    implementation(project(":management-queue"))
    implementation(project(":management-podcast"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.material)
    implementation(libs.dagger)
    implementation(project(":management-urls"))
    implementation(project(":common-utils"))
    ksp(libs.dagger.compiler)

}