plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.component.viewholder"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }
    buildFeatures {
        dataBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}
//todo clean up resources

dependencies {
    //Modules
    implementation(project(":common-base"))
    implementation(project(":common-image"))
    implementation(project(":common-ui-domain"))
    implementation(project(":common-widget"))
    implementation(project(":common-resources") )//todo useful ?
    implementation(project(":feature-podcast-base-domain"))
    implementation(project(":feature-songlist-base-domain"))
    implementation(project(":feature-song-base-domain"))
    implementation(project(":management-queue"))
    //Android
    implementation(libs.androidx.core.ktx)
    implementation(libs.material)
    //DI
    implementation(libs.dagger)
    ksp(libs.dagger.compiler)
    //Lifecycle
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
}
apply plugin: "kotlin-parcelize"