plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.component.image.display"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }
    buildFeatures {
        dataBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    //Modules
    implementation(project(":common-image"))
    implementation(project(":common-base"))
    implementation(project(":common-ui-domain"))
    implementation(project(":common-resources"))
    //Android
    implementation(libs.androidx.core.ktx)
    implementation(libs.material)
    //glide
    implementation(libs.glide)
    ksp(libs.glide.ksp)
    implementation(libs.glide.okhttp3.integration)
    implementation(libs.stfalconimageviewer)
    //Lifecycle
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
}