plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.feature.player.ui"
    compileSdk 36

    defaultConfig {
        minSdk 23

        consumerProguardFiles "consumer-rules.pro"
    }
    buildFeatures {
        dataBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    implementation(project(":common-base"))
    implementation(project(":common-di"))
    implementation(project(":common-image"))
    implementation(project(":common-logging"))
    implementation(project(":common-navigation"))
    implementation(project(":common-resources"))
    implementation(project(":component-menu"))
    implementation(project(":component-player-controls"))
    implementation(project(":data-local"))
    implementation(project(":feature-auth-domain"))
    implementation(project(":feature-player-service"))
    implementation(project(":feature-song-ui"))
    implementation(project(":feature-sync-service"))
    implementation(project(":management-alarm"))
    implementation(project(":management-filters"))
    implementation(project(":management-playlist"))
    implementation(project(":management-podcast"))
    implementation(project(":management-queue"))
    implementation(project(":management-tags"))
    implementation(project(":management-waveform"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.retrofit)
    implementation(libs.androidx.media3.datasource.okhttp)
    implementation(libs.androidx.work.runtime.ktx)
    ksp(libs.dagger.compiler)
    //Paging
    implementation(libs.androidx.paging.runtime.ktx)
    implementation(libs.recyclerview.fastscroll)
    implementation(libs.androidx.media3.session)
    implementation(libs.dagger)
    implementation(libs.androidx.media3.datasource)
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.material)

}