plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
}

android {
    namespace "be.florien.anyflow.management.download"
    compileSdk 36

    defaultConfig {
        minSdk 23

        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    implementation(project(":common-di"))
    implementation(project(":common-logging"))
    implementation(project(":data-local"))
    implementation(project(":management-filters"))
    implementation(project(":management-filters-domain"))
    implementation(project(":management-tags"))
    implementation(project(":management-urls"))

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.livedata.ktx)
    implementation(libs.dagger)
    implementation(libs.retrofit)
}
apply plugin: "kotlin-parcelize"