pluginManagement {
    repositories {
        mavenCentral()
        google()
        maven { url("https://maven.fabric.io/public") }
    }
}

includeBuild("build-scripts")
include ":app"
includeDirectory("common")
includeDirectory("component")
includeDirectory("data")
includeDirectory("feature")
includeDirectory("management")

private void includeDirectory(File directory) {
    directory.eachDir { subDirectory ->
        if (new File(subDirectory, "build.gradle.kts").exists()) {
            def moduleName = subDirectory.name
            include moduleName
            project(":${moduleName}").projectDir = subDirectory
        } else {
            includeDirectory(subDirectory)
        }
    }
}

private void includeDirectory(String directory) {
    includeDirectory(file(directory))
}
