plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.autonomousapps.dependency-analysis"
    alias(libs.plugins.library.compose.plugin)
}

android {
    namespace "be.florien.anyflow.common.navigation"
    compileSdk 36

    defaultConfig {
        minSdk 23

        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    api(libs.androidx.fragment)
    api(project(":common-ui-domain"))
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.navigation3.runtime)
    implementation(libs.androidx.navigation3.ui)
}