plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.autonomousapps.dependency-analysis"
}

android {
    namespace "be.florien.anyflow.common.navigation"
    compileSdk 36

    defaultConfig {
        minSdk 23

        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    api(libs.androidx.fragment)
    api(project(":common-ui-domain"))
}