plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.management.playlist"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    implementation(project(":common-di"))
    implementation(project(":common-logging"))
    implementation(project(":common-management"))
    implementation(project(":common-resources"))
    implementation(project(":common-ui-domain"))
    implementation(project(":common-utils"))
    implementation(project(":data-local"))
    implementation(project(":data-server"))
    implementation(project(":management-filters-domain"))
    implementation(project(":management-urls"))
    //Room
    //todo add another layer of abstraction on top of libraryDatabase in data-local and remove these dependencies
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)

    //Paging
    implementation(libs.androidx.paging.runtime.ktx)

    //Workmanager
    implementation(libs.androidx.work.runtime.ktx)

    //DI
    implementation(libs.dagger)
    ksp(libs.dagger.compiler)
}
apply plugin: "kotlin-parcelize"