plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.autonomousapps.dependency-analysis"
}

android {
    namespace "be.florien.anyflow.common.logging"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    //debug
    implementation(libs.treessence)
    api(libs.timber)
    implementation(libs.firebase.core)
    implementation(libs.firebase.crashlytics)
}