plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.feature.auth.domain"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    implementation(project(":common-di"))
    implementation(project(":data-server"))
    implementation(project(":common-logging"))
    implementation(project(":common-utils"))

    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.livedata.core.ktx)
    // DI
    implementation(libs.dagger)
    ksp(libs.dagger.compiler)
    // Internet
    implementation(libs.okhttp)
    implementation(libs.retrofit.converter.jackson )//todo use standalone jackson library
}