plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.autonomousapps.dependency-analysis"
}

android {
    namespace "be.florien.anyflow.common.utils"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}