package be.florien.ampacheplayer.model.local

import be.florien.ampacheplayer.model.realm.RealmSong
import be.florien.ampacheplayer.model.ampache.AmpacheSong

/**
 * Database structure that represents to songs
 */
data class Song(
        var id: Long = 0,
        var song: String = "",
        var title: String = "",
        var name: String = "",
        var artistName: String = "",
        var artistId: Long = -1,
        var albumName: String = "",
        var albumId: Long = -1,
        var albumArtistName: String = "",
        var albumArtistId: Long = -1,
        var tag: List<Tag> = emptyList<Tag>(),
        var filename: String = "",
        var track: Int = 0,
        var time: Int = 0,
        var year: Int = 0,
        var bitrate: Int = 0,
        var rate: Int = 0,
        var url: String = "",
        var art: String = "",
        var preciserating: Int = 0,
        var rating: Int = 0,
        var averagerating: Int = 0,
        var composer: String = "",
        var comment: String = "",
        var publisher: String = "",
        var language: String = "",
        var genre: String = ""
) {

    constructor(fromServer: AmpacheSong) : this(
            id = fromServer.id,
            song = fromServer.song,
            title = fromServer.title,
            name = fromServer.name,
            artistName = fromServer.artist.name,
            artistId = fromServer.artist.id,
            albumName = fromServer.album.name,
            albumId = fromServer.album.id,
            albumArtistName = fromServer.albumartist.name,
            albumArtistId = fromServer.albumartist.id,
            tag = fromServer.tag.map(::Tag),
            filename = fromServer.filename,
            track = fromServer.track,
            time = fromServer.time,
            year = fromServer.year,
            bitrate = fromServer.bitrate,
            rate = fromServer.rate,
            url = fromServer.url,
            art = fromServer.art,
            preciserating = fromServer.preciserating,
            rating = fromServer.rating,
            averagerating = fromServer.averagerating,
            composer = fromServer.composer,
            comment = fromServer.comment,
            publisher = fromServer.publisher,
            language = fromServer.language,
            genre = fromServer.genre)

    constructor(fromRealm: RealmSong) : this(
            id = fromRealm.id,
            song = fromRealm.song,
            title = fromRealm.title,
            name = fromRealm.name,
            artistName = fromRealm.artistName,
            artistId = fromRealm.artistId,
            albumName = fromRealm.albumName,
            albumId = fromRealm.albumId,
            albumArtistName = fromRealm.albumArtistName,
            albumArtistId = fromRealm.albumArtistId,
            tag = fromRealm.tag.map(::Tag),
            filename = fromRealm.filename,
            track = fromRealm.track,
            time = fromRealm.time,
            year = fromRealm.year,
            bitrate = fromRealm.bitrate,
            rate = fromRealm.rate,
            url = fromRealm.url,
            art = fromRealm.art,
            preciserating = fromRealm.preciserating,
            rating = fromRealm.rating,
            averagerating = fromRealm.averagerating,
            composer = fromRealm.composer,
            comment = fromRealm.comment,
            publisher = fromRealm.publisher,
            language = fromRealm.language,
            genre = fromRealm.genre)
}
