plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.autonomousapps.dependency-analysis'
    id 'kotlin-kapt'
}

android {
    namespace 'be.florien.anyflow.common.base'
    compileSdk 34

    defaultConfig {
        minSdk 23
    }
    buildFeatures {
        dataBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    api project(':common-ui-domain')

    api 'androidx.fragment:fragment:1.5.4'
    api 'androidx.lifecycle:lifecycle-livedata-core:2.7.0'
    api 'androidx.lifecycle:lifecycle-viewmodel:2.7.0'
    api 'androidx.recyclerview:recyclerview:1.2.1'
    api 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3'
    implementation 'androidx.annotation:annotation:1.8.0'
    implementation 'androidx.databinding:databinding-common:8.7.2'
    implementation 'androidx.core:core:1.13.1'
}