plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.autonomousapps.dependency-analysis'
}

android {
    namespace 'be.florien.anyflow.common.widget'
    compileSdk 34

    defaultConfig {
        minSdk 23
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
}

dependencies {
    api 'androidx.constraintlayout:constraintlayout:2.0.1'
}
apply plugin: 'kotlin-parcelize'