plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "kotlin-kapt"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.feature.songlist.ui"
    compileSdk 36

    defaultConfig {
        minSdk 23

        consumerProguardFiles "consumer-rules.pro"
    }
    buildFeatures {
        dataBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    implementation(project(":common-di"))
    implementation(project(":common-image"))
    implementation(project(":common-navigation"))
    implementation(project(":common-base"))
    implementation(project(":common-logging"))
    implementation(project(":common-ui-domain"))
    implementation(project(":common-widget"))
    implementation(project(":component-menu"))
    implementation(project(":component-viewholder"))
    implementation(project(":data-local"))
    implementation(project(":feature-song-base-ui"))
    implementation(project(":feature-song-ui"))
    implementation(project(":feature-player-service"))
    implementation(project(":feature-podcast-base-domain"))
    implementation(project(":feature-songlist-base-domain"))
    implementation(project(":feature-song-base-domain"))
    implementation(project(":feature-song-domain"))
    implementation(project(":feature-podcast-ui"))
    implementation(project(":feature-podcast-base-ui"))
    implementation(project(":management-download"))
    implementation(project(":management-filters"))
    implementation(project(":management-podcast"))
    implementation(project(":management-queue"))
    implementation(project(":management-tags"))
    implementation(project(":management-urls"))

    //Paging
    implementation(libs.androidx.paging.runtime.ktx)
    implementation(libs.recyclerview.fastscroll)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.material)
    implementation(libs.dagger)
    implementation(libs.androidx.media3.session)
    implementation(libs.androidx.navigation.common.ktx)
    ksp(libs.dagger.compiler)

}