plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}

android {
    namespace 'be.florien.anyflow.feature.player.service'
    compileSdk 34

    defaultConfig {
        minSdk 23

        consumerProguardFiles "consumer-rules.pro"
    }
    buildFeatures {
        dataBinding = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
}

dependencies {
    implementation project(':common-di')
    implementation project(':data-local')
    implementation project(':management-filters')
    implementation project(':management-playlist')
    implementation project(':management-podcast')
    implementation project(':management-tags')
    implementation project(':management-alarm')
    implementation project(':management-queue')
    implementation project(':management-urls')
    implementation project(':management-waveform')

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation project(':management-filters-domain')
    kapt "com.google.dagger:dagger-compiler:$dagger_version"
    //Paging
    implementation 'androidx.paging:paging-runtime-ktx:3.2.1'
    implementation 'com.simplecityapps:recyclerview-fastscroll:2.0.1'
    implementation "com.google.dagger:dagger:$dagger_version"
    implementation 'androidx.media3:media3-session:1.5.1'
    implementation "androidx.media3:media3-datasource-okhttp:1.5.1"
    implementation 'androidx.media3:media3-datasource:1.5.1'
    implementation 'androidx.media3:media3-exoplayer:1.5.1'
    implementation "androidx.media3:media3-common-ktx:1.5.1"

}