plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.google.devtools.ksp"
    id "kotlin-kapt"
    id "com.autonomousapps.dependency-analysis"
}

android {
    namespace "be.florien.anyflow.common.image"
    compileSdk 36

    defaultConfig {
        minSdk 23
    }
    buildFeatures {
        dataBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    //Modules
    api(project(":common-ui-domain"))
    implementation(project(":common-resources"))
    //Android
    api(libs.androidx.fragment)
    api(libs.okhttp)
    api(libs.javax.inject)
    implementation(libs.androidx.annotation)
    implementation(libs.glide.annotations)
    //glide
    api(libs.glide)
    ksp(libs.glide.ksp)
    implementation(libs.glide.okhttp3.integration)
    //DI
    api(libs.dagger)
    ksp(libs.dagger.compiler)
}
apply plugin: "kotlin-parcelize"