plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'com.autonomousapps.dependency-analysis'
}

android {
    namespace 'be.florien.anyflow.common.ui.domain'
    compileSdk 34

    defaultConfig {
        minSdk 23

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
}
dependencies {
    implementation 'androidx.annotation:annotation:1.6.0'
    implementation 'org.jetbrains.kotlin:kotlin-parcelize-runtime:1.9.20'
}
apply plugin: 'kotlin-parcelize'