plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.autonomousapps.dependency-analysis"
}

android {
    namespace "be.florien.anyflow.common.ui.domain"
    compileSdk 36

    defaultConfig {
        minSdk 23

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}
dependencies {
    implementation(libs.androidx.annotation)
    implementation(libs.kotlin.parcelize.runtime)
}
apply plugin: "kotlin-parcelize"