plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.android"
    id "com.google.devtools.ksp"
}

android {
    namespace "be.florien.anyflow.data.local"
    compileSdk 36 //todo common version

    defaultConfig {
        minSdk 23
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = "21"
    }
}

dependencies {
    implementation(project(":common-logging"))
    implementation(project(":common-utils"))
    implementation(project(":management-filters-domain"))
    implementation(libs.dagger)
    ksp(libs.dagger.compiler)
    //LiveData
    implementation(libs.androidx.lifecycle.livedata.ktx)
    //Paging
    implementation(libs.androidx.paging.runtime.ktx)
    //Room
//    implementation("androidx.room:room-common:$room_version")
    implementation(libs.androidx.room.ktx)
    implementation(libs.androidx.room.runtime)
    ksp(libs.androidx.room.compiler)
    // Required -- JUnit 4 framework
    testImplementation(libs.junit)
}